GiDi_Siemens_WebServer/Models/ErrorViewModel.cs
using System;

namespace Siemens.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GiDi_Siemens_WebServer/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Luca;
using GiDi_SiemensApp.Siemens;
using System.IO;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GiDi_SiemensApp.Controllers
{
    public class AjaxController : Controller
    {
        private readonly IViewRenderService _viewRenderService;

        public AjaxController(IViewRenderService viewRenderService)
        {
            _viewRenderService = viewRenderService;
        }

        public void OpenPlcConnection()
        {
            try
            {
                if (!Repo.SiemensPlc.Plc.IsConnected)
                {
                    Repo.SiemensPlc.Plc.Open();
                    //dentro il read asynk lo fermo fin quando non deve ripartire
                    Repo.SiemensPlc.AsyncReadAllVariables();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Startup.Startup.OnApplicationStarted = " + ex.Message);
            }
        }

        public int GetStatus()
        {
            try
            {
                bool isAvailable = Siemens.Repo.SiemensPlc.Plc.IsAvailable;
                bool isConnected = Siemens.Repo.SiemensPlc.Plc.IsConnected;
                if (!isAvailable) return 0;
                if (isAvailable && !isConnected) return 1;
                if (isAvailable && isConnected) return 2;

            }
            catch (Exception ex)
            {
                Console.WriteLine("AjaxController.GetStatus = " + ex.Message);
            }
            return -1; //errore
        }

        public JsonResult GetDb1(int a)
        {
            try
            {
                var result = _viewRenderService.RenderToStringAsync("/Views/Home/GetDb1.cshtml", Repo.SiemensPlc);
                return Json(result.Result);
            }
            catch (Exception ex)
            {

                return Json(ex.Message);
            }

        }

        /// <summary>
        /// Scrittura di una determinata variabile, all'interno della classe del repository e successivamente
        /// all'interno del PLC
        /// </summary>
        /// <param name="aj">parametro inviato dal post ajax</param>
        public void Write(AjaxUpater aj)
        {
            if (!Repo.SiemensPlc.Plc.IsConnected) Repo.SiemensPlc.Plc.Open();
            //Se è stato passato un modello in post
            if (Request.Method == "POST")
            {
                object a = Luca.Siemens.Functons.RebuildTheBlackBox(aj.Content, Repo.SiemensPlc.Data[aj.Index].DotNetDataType);
                Repo.SiemensPlc.Data[aj.Index].RawContent = a;

                if (Repo.SiemensPlc.Data[aj.Index].VariableType == S7.Net.VarType.String)
                {
                    Repo.SiemensPlc.Data[aj.Index].Content = a;
                    Repo.SiemensPlc.BuildRawString_FromWork(Repo.SiemensPlc.Data[aj.Index]);
                }
                else
                {
                    Repo.SiemensPlc.Data[aj.Index].RawContent = a;
                }
                //Scrivo a questo punto la variabile nel PLC
                Repo.SiemensPlc.WriteSingleVaraible(aj.Index);
            }
        }

        public class AjaxUpater
        {
            public int Index { get; set; }
            public string Content { get; set; }
        }


    }
}

GiDi_Siemens_WebServer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GiDi_SiemensApp.Siemens;
using Siemens.Models;

namespace GiDi_SiemensApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SiemensTag()
        {
            return View(Repo.SiemensPlc);
        }

        public IActionResult MonitorSiemens()
        {
            ViewData["Message"] = "PLC Siemens s7-1200 - GiDi Automazione";
            return View();
        }

        public IActionResult WriteSiemensPLC()
        {
            ViewData["Message"] = "Scrittura variabili su PLC s7-1200";
            //Leggo dal PLC e compongo la classe work
            return View(Repo.SiemensPlc.Data);
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GiDi_Siemens_WebServer/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contatti GiDi";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<link rel="stylesheet" href="~/css/info.css"/>

<script>
      function initMap() {
        var uluru = {lat: 45.6235119, lng: 9.2129414};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 9,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBmLZs__43VF98iqY2HLipdjpPivgI_sg&callback=initMap">
</script>


<div class="mapContainer lightShadow">
    <div id="map"></div>
</div>

<div class="infoWrapper">

    <article class="doveSiamoArticle infoArticle">
        <header><img class="transition03" src="~/images/map.svg">Indirizzo</header>
        <p>Via Volta 94, Desio (MB), CAP 20832</p>
    </article>

    <article class="telefonoArticle infoArticle">
        <header><img class="transition03" src="~/images/tel.svg">Telefono</header>
        <p>0362 62 41 13</p>
    </article>

    <article class="emailArticle infoArticle">
        <header><img class="transition03" src="~/images/contattiBlu.svg">E-Mail</header>

        <table class="emailTable">
            <tr>
                <td>Info</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:info@gidiautomazione.it" target="_blank">info@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Ufficio - Chiara</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:chiara@gidiautomazione.it" target="_blank">chiara@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Ordini</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:commerciale@gidiautomazione.it" target="_blank">commerciale@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Danilo Cattaldo</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:danilo@gidiautomazione.it" target="_blank">danilo@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Luca Gilardi</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:luca.gilardi@gidiautomazione.it" target="_blank">luca.gilardi@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Michele Torrentino</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:michele.torrentino@gidiautomazione.it" target="_blank">michele.torrentino@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Raffaele Tufano</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:raffaele@gidiautomazione.it" target="_blank">raffaele@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Simone Greco</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:simone@gidiautomazione.it" target="_blank">simone@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Andrea Scroppo</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:andrea.scroppo@gidiautomazione.it" target="_blank">andrea.scroppo@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Andrea Suriano</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:andrea.suriano@gidiautomazione.it" target="_blank">andrea.suriano@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Luca Mori</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:luca.mori@gidiautomazione.it" target="_blank">luca.mori@gidiautomazione.it</td>
            </tr>
            <tr>
                <td>Marco Cattaldo</td>
                <td class="bull">&bull;</td>
                <td class="email transition03"><a href="mailto:marco.cattaldo@gidiautomazione.it" target="_blank">marco.cattaldo@gidiautomazione.it</td>
            </tr>
        </table>
    </article>

</div>

GiDi_Siemens_WebServer/Views/Home/GetDb1.cshtml
@model Luca.Siemens.Models.SiemensPLC
@{
    ViewData["Title"] = "ReadSiemensPLC";
}

<div class="list-group">
    <a class="list-group-item text-center active">Valori Tag PLC Live</a>

    @foreach (var item in Model.Data)
    {
        if (item.DotNetDataType != typeof(string))
        {
            <a class="list-group-item list-group-item-action">Nome Variabile : @item.Name Valore : @item.RawContent</a>
        }
        else if (item.DotNetDataType == typeof(string))
        {
            <a class="list-group-item list-group-item-action">Nome Variabile : @item.Name Valore : @item.Content</a>
        }
    }
            <a class="list-group-item list-group-item-action">
                @Model.Data[0].Name : 
                <div class="progress">
                    <div id="bar" class="progress-bar no-animation" role="progressbar" style="width: @Model.Data[0].RawContent%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">@Model.Data[0].RawContent</div>
                </div>
            </a>
</div>

GiDi_Siemens_WebServer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="jumbotron" style="margin-top:20px;">
    <h1 class="display-4">Gi.Di. Automazione</h1>
    <p class="lead">Esempio applicazione Web-Server per comunicazione PLC Siemens S7-1200</p>
    <hr class="my-4">
    <p>Monitoraggio in tempo reale del PLC</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="Home/MonitorSiemens" role="button">Vai al Monitor</a>
    </p>
</div>

GiDi_Siemens_WebServer/Views/Home/MonitorSiemens.cshtml
@{
    ViewData["Title"] = "Monitor PLC Siemens";
}
<h2>@ViewData["Title"]</h2>

<div id="ajaxContainer">
</div>
<div class="loader"></div>

<script>
    function LoadDataa()
    {
        $.ajax({
            type: "POST",
            url: "../Ajax/GetDb1",
            data: '',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: DataLoaded,
            failure: function (response) {
                alert(response.d);
            }
        });
    }

    function DataLoaded(response) {
        //console.log("fatto");
        //console.log(response);
        $(".loader").hide();
        $("#ajaxContainer").html(response);
    }

    window.setInterval(LoadDataa, 1500);
</script>
<style>
    .loader {
        border: 16px solid #f3f3f3; /* Light grey */
        border-top: 16px solid #3498db; /* Blue */
        border-radius: 50%;
        width: 120px;
        height: 120px;
        animation: spin 2s linear infinite;
        margin: auto;
    }

    @@keyframes spin {
        0% {
            transform: rotate(0deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }
</style>

GiDi_Siemens_WebServer/Views/Home/SiemensTag.cshtml
@model Luca.Siemens.Models.SiemensPLC

@{
    ViewData["Title"] = "SiemensTag";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SiemensTag</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-5">
            <div class="list-group">
                <a class="list-group-item text-center active" data-remote="true" href="#" id="categoria_0">
                    Tags PLC Siemens
                </a>

                @for (int i = 0; i < Model.Data.Count; i++)
                {
                    <a class="list-group-item " data-remote="true" href="#sub_categoria_@i" id="categoria_@i" data-toggle="collapse" data-parent="#sub_categoria_@i" style="padding-left: 25px;">
                        <span class="fas fa-tags fa-lg fa-fw " style="color:cornflowerblue"></span>
                        <span style="margin-left: 25px;">@Model.Data[i].Name</span>
                        <span class="menu-ico-collapse"><i class="fa fa-chevron-down" style="margin-right: 5px;float: right;"></i></span>
                    </a>

                    <div class="collapse list-group-submenu" id="sub_categoria_@i">
                        <a href="#" class="list-group-item sub-item" data-parent="#sub_categoria_@i" style="padding-left: 78px;">Nome : @Model.Data[i].Name</a>
                        <a href="#" class="list-group-item sub-item" data-parent="#sub_categoria_@i" style="padding-left: 78px;">Numero DB : @Model.Data[i].DBNumber</a>
                        <a href="#" class="list-group-item sub-item" data-parent="#sub_categoria_@i" style="padding-left: 78px;">Offset Database : @Model.Data[i].DBOffset</a>
                        <a href="#" class="list-group-item sub-item" data-parent="#sub_categoria_@i" style="padding-left: 78px;">Tipo Variabile Siemens: @Model.Data[i].VariableType</a>
                        <a href="#" class="list-group-item sub-item" data-parent="#sub_categoria_@i" style="padding-left: 78px;">Tipo Variabile DotNet: @Model.Data[i].DotNetDataType</a>
                    </div>


                }

            </div>
        </div>
    </div>
</div>

<style>
    /* CSS used here will be applied after bootstrap.css */
    .menu-ico-collapse {
        margin-left: 4px;
    }

    .list-group-submenu .list-group-item:first-child {
        border-top-right-radius: 0;
        border-top-left-radius: 0;
    }

    .list-group-submenu .list-group-item:last-child {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }
</style>

GiDi_Siemens_WebServer/Views/Home/WriteSiemensPLC.cshtml
@model List<Luca.Siemens.Models.SiemensTag>
@{
    ViewData["Title"] = "Scrittura Tags PLC Siemens";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewData["Title"]</h2>

<div class="list-group">
    <a class="list-group-item text-center active">Tags PLC</a>

    @for (int i = 0; i < Model.Count; i++)
    {
        <a class="list-group-item list-group-item-action">
            <p>Nome Tag : @Model[i].Name</p>
            <form asp-controller="Ajax" asp-action="Write" data-ajax="true" data-ajax-method="POST">


                @if (Model[i].VariableType == S7.Net.VarType.String)
                {
                    <span><input type="text" name="Content" value="@Model[i].Content" maxlength="@Model[i].MaxStringLenght" /></span>
                }
                else if (Model[i].VariableType == S7.Net.VarType.Int && Model[i].DotNetDataType == typeof(Int16))
                {
                    <span><input type="number" name="Content" value="@Model[i].RawContent" max="@Int16.MaxValue" min="@Int16.MinValue" /></span>
                }
                else if (Model[i].VariableType == S7.Net.VarType.Int && Model[i].DotNetDataType == typeof(UInt16))
                {
                    <span><input type="number" name="Content" value="@Model[i].RawContent" max="@UInt16.MaxValue" min="@UInt16.MinValue" /></span>
                }
                else if (Model[i].VariableType == S7.Net.VarType.DWord && Model[i].DotNetDataType == typeof(Int32))
                {
                    <span><input type="number" name="Content" value="@Model[i].RawContent" max="@Int32.MaxValue" min="@Int32.MinValue" /></span>
                }
                else if (Model[i].VariableType == S7.Net.VarType.DWord && Model[i].DotNetDataType == typeof(UInt32))
                {
                    <span><input type="number" name="Content" value="@Model[i].RawContent" max="@UInt32.MaxValue" min="@UInt32.MinValue" /></span>
                }
                else if (Model[i].VariableType == S7.Net.VarType.Real && Model[i].DotNetDataType == typeof(Single))
                {
                    <span><input type="number" name="Content" value="@(Math.Truncate((double)Model[i].RawContent*1000)/1000)" max="@Single.MaxValue" min="@Single.MinValue" step="0.1" /></span>
                }
                else if (Model[i].VariableType == S7.Net.VarType.Real && Model[i].DotNetDataType == typeof(double))
                {
                    <span><input type="number" name="Content" value="@(Math.Truncate((double)Model[i].RawContent*1000)/1000)" max="@double.MaxValue" min="@double.MinValue" step="0.1" /></span>
                }
                <span><input type="number" name="Index" value="@i" hidden="hidden" /></span>
                <span><input type="submit" hidden="hidden" /></span>
            </form>
        </a>
    }

</div>

GiDi_Siemens_WebServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GiDiSiemens</title>
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/jquery/jquery.unobtrusive-ajax.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img src="~/images/LogoGIDI.svg" alt="Logo GiDi Automazione" style="height : 100%; float:left; margin-right:5px;" /> GiDi Automazione [ Siemens ]
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="SiemensTag">Tags PLC</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="MonitorSiemens">Monitor</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="WriteSiemensPLC">Scrittura Nuova Ricetta</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a><i id="connectionIcon" class="fas fa-plug fa-lg noConnection"></i></a></li>


                </ul>
            </div>

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Gi.Di. Automazione</p>

        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    <script>
        function x() {
            console.log("getStatus");
            $.ajax({
                type: "Get",
                url: "../Ajax/GetStatus",
                data: '',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: a,
                failure: function (response) {
                    alert(response.d);
                }
            });
        }

        function a(response) {
            console.log(response);
            if (response == -1) $("#connectionIcon").css('color', 'purple');
            if (response == 0) $("#connectionIcon").css('color', 'red');
            if (response == 1) $("#connectionIcon").css('color', 'orange');
            if (response == 2) $("#connectionIcon").css('color', 'forestgreen');
        }

        window.setInterval(x, 3000);
    </script>
</body>
</html>